//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThoughtWorks.RailRoad.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThoughtWorks.RailRoad.UI.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([{0}] - Distance: {1}).
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. The distance of the route [{1}]: {2}.
        /// </summary>
        internal static string DistanceRoutesResponse {
            get {
                return ResourceManager.GetString("DistanceRoutesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exactly {0} stops.
        /// </summary>
        internal static string ExactlyStops {
            get {
                return ResourceManager.GetString("ExactlyStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Generated routes:.
        /// </summary>
        internal static string GeneratedRotes {
            get {
                return ResourceManager.GetString("GeneratedRotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a maximum of {0} stops.
        /// </summary>
        internal static string MaxStops {
            get {
                return ResourceManager.GetString("MaxStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///*The requiments of this question says that just exists 7 routes, but the right value is {0}.
        /// </summary>
        internal static string Question10Notes {
            get {
                return ResourceManager.GetString("Question10Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. The number of different routes from C to C with a distance of less than 30: {0}. {1} {2}.
        /// </summary>
        internal static string Question10Response {
            get {
                return ResourceManager.GetString("Question10Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. The length of the shortest route from {1} to {2}: {3} (route {4})..
        /// </summary>
        internal static string ShortestRouteQuestionResponse {
            get {
                return ResourceManager.GetString("ShortestRouteQuestionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. The number of trips starting at {1} and ending at {2} with {3}: {4}. {5}.
        /// </summary>
        internal static string StopQuestionResponse {
            get {
                return ResourceManager.GetString("StopQuestionResponse", resourceCulture);
            }
        }
    }
}
